apiVersion: v1
data:
  OPERATIONAL_MODE: STANDALONE
  PING_IDENTITY_ACCEPT_EULA: "YES"
  SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
  SERVER_PROFILE_PATH: getting-started/pingfederate
  # http_proxy: http://sqpx.mge.spratingsvpc.com:10041
  # https_proxy: http://sqpx.mge.spratingsvpc.com:10041
  # NO_PROXY: 10.,localhost,127.0.0.1,169.254.169.254,.internal,172.20.0.0/16,s3.amazonaws.com,.s3.amazonaws.com,s3.us-east-1.amazonaws.com,.s3.us-east-1.amazonaws.com,.eks.amazonaws.com,.svc
kind: ConfigMap
metadata:
  name: pingfederate-variables
---
apiVersion: v1
kind: Service
metadata:
  name: pingfederate-lb
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
  labels:
    app: pingfederate
    tier: standalonw
spec:
  ports:
    - port: 9999
      name: console
      protocol: TCP
      targetPort: 9999
    - port: 443
      name: engine
      protocol: TCP
      targetPort: 9031
  selector:
    app: pingfederate
    tier: standalone
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingfederate
  labels:
    app: pingfederate
    tier: standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingfederate
      tier: standalone
  template:
    metadata:
      labels:
        app: pingfederate
        tier: standalone
    spec:
      containers:
        - name: pingfederate
          image: pingidentity/pingfederate:10.0.0-alpine-edge
          ports:
            - containerPort: 9999
          resources:
            requests:
              memory: "1.5Gi"
              cpu: "1"
            limits:
              memory: "1.5Gi"
              cpu: "1"
          envFrom:
            - configMapRef:
                name: pingfederate-variables
            - secretRef:
                name: devops-secret
                optional: true
