apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-environment
  labels:
    app: alpine
data:
  http_proxy: http://192.168.71.102:8888
  https_proxy: http://192.168.71.102:8888
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
    - name: alpine
      image: alpine:3.2
      command:
        - /bin/sh
        - "-c"
        - "sleep 60m"
      imagePullPolicy: IfNotPresent
      envFrom:
        - configMapRef:
            name: proxy-environment
