apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-environment
  labels:
    app: alpine
data:
  - name: HTTPS_PROXY
    valueFrom:
      configMapKeyRef:
        key: HTTPS_PROXY
        name: proxy-environment-variables
  - name: HTTP_PROXY
    valueFrom:
      configMapKeyRef:
        key: HTTP_PROXY
        name: proxy-environment-variables
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
    - name: alpine
      image: alpine:3.2
      command:
        - /bin/sh
        - "-c"
        - "sleep 60m"
      imagePullPolicy: IfNotPresent
      envFrom:
        - configMapRef:
            name: proxy-environment
