apiVersion: v1
data:
  ACCESS_GRANT_MANAGER_STORE: "org.sourceid.oauth20.token.AccessGrantManagerLDAPPingDirectoryImpl" # PingDirectory
  # ACCESS_GRANT_MANAGER_STORE: "org.sourceid.oauth20.token.AccessGrantManagerJdbcImpl" # Hypersonic
  JETTY_THREAD_MIN: "10" # available cpu cores * 12
  JETTY_THREAD_MAX: "200" # avaliable cpu cores * 25
  JVM_HEAP_MIN: "1024m"
  JVM_HEAP_MAX: "1024m"
  JVM_NEW_SIZE: "512m" # 50% of heap
  PF_DNS_PING_CLUSTER: _bind-port._tcp.pf-cluster-dns
  PF_DNS_PING_NAMESPACE: ping-cloud-devops-eks-mdeller
  PF_DNS_PING_RECORDTYPE: SRV
  OPERATIONAL_MODE: CLUSTERED_CONSOLE
  PING_IDENTITY_ACCEPT_EULA: "YES"
  SERVER_PROFILE_URL: https://github.com/mdeller-ping/pf-performance.git
  SERVER_PROFILE_PATH: server-profiles/pingfederate
kind: ConfigMap
metadata:
  name: console-variables
---
apiVersion: v1
kind: Service
metadata:
  name: pf-console-lb
  labels:
    app: pf-cluster
    tier: console
spec:
  ports:
    #NOTE: external port is 443 now
    - port: 443
      protocol: TCP
      targetPort: 9999
  selector:
    app: pf-cluster
    tier: console
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: pf-cluster-dns
  labels:
    run: pf-cluster
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - name: bind-port
      port: 7600
      protocol: TCP
      targetPort: 7600
  selector:
    app: pf-cluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pf-cluster-console
  labels:
    app: pf-cluster
    tier: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pf-cluster
      tier: console
  template:
    metadata:
      labels:
        app: pf-cluster
        tier: console
    spec:
      containers:
        - name: console-node
          image: pingidentity/pingfederate:10.0.0-alpine-edge
          ports:
            - containerPort: 9999
          resources:
            requests:
              memory: "1.5Gi"
              cpu: "1"
            limits:
              memory: "1.5Gi"
              cpu: "1"
          envFrom:
            - configMapRef:
                name: console-variables
            - secretRef:
                name: devops-secret
                optional: true
