apiVersion: v1
data:
  ACCESS_GRANT_MANAGER_STORE: "org.sourceid.oauth20.token.AccessGrantManagerLDAPPingDirectoryImpl" # PingDirectory
  # ACCESS_GRANT_MANAGER_STORE: "org.sourceid.oauth20.token.AccessGrantManagerJdbcImpl" # Hypersonic
  JETTY_THREAD_MIN: "10" # available cpu cores * 12
  JETTY_THREAD_MAX: "200" # avaliable cpu cores * 25
  JVM_HEAP_MIN: "1024m"
  JVM_HEAP_MAX: "1024m"
  JVM_NEW_SIZE: "512m" # 50% of heap
  PF_DNS_PING_CLUSTER: _bind-port._tcp.pf-cluster-dns
  PF_DNS_PING_NAMESPACE: ping-cloud-devops-eks-mdeller
  PF_DNS_PING_RECORDTYPE: SRV
  OPERATIONAL_MODE: CLUSTERED_CONSOLE
  PING_IDENTITY_ACCEPT_EULA: "YES"
  SERVER_PROFILE_URL: https://github.com/mdeller-ping/pf-performance.git
  SERVER_PROFILE_PATH: server-profiles/pingfederate
kind: ConfigMap
metadata:
  name: console-variables
