apiVersion: v1
kind: Service
metadata:
  name: pf-engine-lb
  labels:
    app: pf-cluster
    tier: engine
spec:
  ports:
    #NOTE: external port is 443 now
    - port: 443
      protocol: TCP
      targetPort: 9031
  selector:
    app: pf-cluster
    tier: engine
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: pf-cluster-dns
  labels:
    run: pf-cluster
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - name: bind-port
      port: 7600
      protocol: TCP
      targetPort: 7600
  selector:
    app: pf-cluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pf-cluster-engine
  labels:
    app: pf-cluster
    tier: engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pf-cluster
      tier: engine
  template:
    metadata:
      labels:
        app: pf-cluster
        tier: engine
    spec:
      containers:
        - name: engine-node
          image: pingidentity/pingfederate:10.0.0-alpine-edge
          ports:
            - containerPort: 9031
          resources:
            requests:
              memory: "8Gi"
              cpu: "12"
            limits:
              memory: "8Gi"
              cpu: "12"
          envFrom:
            - configMapRef:
                name: engine-variables
            - secretRef:
                name: devops-secret
                optional: true
