apiVersion: v1
data:
  OPERATIONAL_MODE: CLUSTERED_ENGINE
  PF_DNS_PING_CLUSTER: _bind-port._tcp.pf-cluster-dns
  PF_DNS_PING_NAMESPACE: default
  PF_DNS_PING_RECORDTYPE: SRV
  PING_IDENTITY_ACCEPT_EULA: "YES"
  SERVER_PROFILE_URL: https://github.com/mdeller-ping/poc-vanilla.git
  SERVER_PROFILE_PATH: server-profiles/pingfederate
  http_proxy: http://sqpx.mge.spratingsvpc.com:10041
  https_proxy: http://sqpx.mge.spratingsvpc.com:10041
  NO_PROXY: 10.,localhost,127.0.0.1,169.254.169.254,.internal,172.20.0.0/16,s3.amazonaws.com,.s3.amazonaws.com,s3.us-east-1.amazonaws.com,.s3.us-east-1.amazonaws.com,.eks.amazonaws.com,.svc
kind: ConfigMap
metadata:
  name: engine-variables
---
apiVersion: v1
kind: Service
metadata:
  name: pf-engine-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
  labels:
    app: pf-cluster
    tier: engine
spec:
  ports:
    #NOTE: external port is 443 now
    - port: 443
      protocol: TCP
      targetPort: 9031
  selector:
    app: pf-cluster
    tier: engine
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: pf-cluster-dns
  labels:
    run: pf-cluster
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - name: bind-port
      port: 7600
      protocol: TCP
      targetPort: 7600
  selector:
    app: pf-cluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pf-cluster-engine
  labels:
    app: pf-cluster
    tier: engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pf-cluster
      tier: engine
  template:
    metadata:
      labels:
        app: pf-cluster
        tier: engine
    spec:
      containers:
        - name: engine-node
          image: pingidentity/pingfederate:10.0.0-alpine-edge
          ports:
            - containerPort: 9031
          resources:
            requests:
              memory: "1.5Gi"
              cpu: "1"
            limits:
              memory: "1.5Gi"
              cpu: "1"
          envFrom:
            - configMapRef:
                name: engine-variables
            - secretRef:
                name: devops-secret
                optional: true
