apiVersion: v1
data:
  PING_IDENTITY_ACCEPT_EULA: "YES"
  SERVER_PROFILE_PATH: server-profiles/pingaccess
  SERVER_PROFILE_URL: https://www.github.com/mdeller-ping/poc-vanilla.git
kind: ConfigMap
metadata:
  labels:
    role: pingaccess
  name: pingaccess-environment-variables
---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingaccess
  name: pingaccess
spec:
  ports:
    - name: pa-admin
      port: 9000
    - name: pa-app
      port: 443
  selector:
    role: pingaccess
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: pingaccess
  name: pingaccess
spec:
  replicas: 1
  selector:
    matchLabels:
      role: pingaccess
  template:
    metadata:
      labels:
        role: pingaccess
      name: pingaccess
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: pingaccess-environment-variables
            - secretRef:
                name: devops-secret
                optional: true
          image: pingidentity/pingaccess:6.0.0-alpine-edge
          imagePullPolicy: Always
          name: pingaccess
          ports:
            - containerPort: 9000
            - containerPort: 443
          resources:
            limits:
              cpu: "1"
              memory: 1.5Gi
            requests:
              cpu: "1"
              memory: 1.5Gi
